const loader=document.getElementById('loader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),500));
const menuBtn=document.getElementById('menuBtn'),navLinks=document.getElementById('navLinks');menuBtn.addEventListener('click',()=>{navLinks.classList.toggle('open');menuBtn.innerHTML=navLinks.classList.contains('open')?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'});document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>navLinks.classList.remove('open')));
const words=['Modern Websites','Responsive Interfaces','Creative Experiences'];let word=0,char=0,deleting=false;const typing=document.getElementById('typing');function type(){const current=words[word];typing.textContent=current.slice(0,char);if(!deleting&&char<current.length){char++;setTimeout(type,90)}else if(!deleting&&char===current.length){deleting=true;setTimeout(type,1200)}else if(deleting&&char>0){char--;setTimeout(type,50)}else{deleting=false;word=(word+1)%words.length;setTimeout(type,250)}}type();
const reveals=document.querySelectorAll('.reveal');const revealObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.15});reveals.forEach(el=>revealObs.observe(el));
const skillSpans=document.querySelectorAll('.skill-track span');const skillObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.style.width=e.target.dataset.width}),{threshold:.5});skillSpans.forEach(el=>skillObs.observe(el));
const counters=document.querySelectorAll('.counter');let counted=false;const stats=document.querySelector('.stats');const countObs=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!counted){counted=true;counters.forEach(c=>{const target=+c.dataset.target;let n=0;const step=Math.max(1,Math.ceil(target/45));const timer=setInterval(()=>{n+=step;if(n>=target){n=target;clearInterval(timer)}c.textContent=n+'+'},35)})}},{threshold:.45});countObs.observe(stats);
const header=document.getElementById('header'),backTop=document.getElementById('backTop'),sections=document.querySelectorAll('main section[id]'),links=document.querySelectorAll('.nav-link');window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>40);backTop.classList.toggle('show',scrollY>500);let current='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))});
const form=document.getElementById('contactForm'),formMessage=document.getElementById('formMessage');form.addEventListener('submit',e=>{e.preventDefault();formMessage.textContent='Message ready! Connect this form to Formspree or your backend to receive emails.';form.reset()});
const dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');window.addEventListener('mousemove',e=>{dot.style.left=ring.style.left=e.clientX+'px';dot.style.top=ring.style.top=e.clientY+'px'});document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{ring.style.width='52px';ring.style.height='52px'});el.addEventListener('mouseleave',()=>{ring.style.width='34px';ring.style.height='34px'})});
